DROP DATABASE IF EXISTS team_db;
CREATE DATABASE team_db;

USE team_db;

CREATE TABLE department(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
department_name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE employee_roles (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) UNIQUE NOT NULL,
salary INT UNSIGNED NOT NULL,
department_id INT UNSIGNED NOT NULL,
FOREIGN KEY (department_id)
REFERENCES(department(id))
ON DELETE SET NULL
);

CREATE TABLE employee(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) UNIQUE NOT NULL,
last_name VARCHAR(30) UNIQUE NOT NULL,
role_id INT UNSIGNED NOT NULL,
FOREIGN KEY (role_id)
REFERENCES(employee_roles(id))
ON DELETE SET NULL
manager_id INT UNSIGNED,
FOREIGN KEY(manager_id)
REFERENCES(employee(id))
ON DELETE SET NULL
);
USE team_db;

